# Generated by Django 5.1.2 on 2024-12-02 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_messageid_messages_messageid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='answerId',
            field=models.ForeignKey(blank=True, db_column='answerId', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.answers'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='close',
            field=models.BooleanField(default=False, verbose_name='是否关闭'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='static/img/default.jpg', upload_to='static/img/'),
        ),
    ]
