# Generated by Django 5.0.7 on 2024-12-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_messages_messageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.CharField(default='https://s2.loli.net/2024/12/08/MeOiLyYdNt7wK5E.png', max_length=250),
        ),
    ]
