# Generated by Django 5.1.2 on 2024-11-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
