# Generated by Django 5.0.7 on 2024-11-24 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='MessageId',
            new_name='messageId',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='Read',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='noticemessages',
            old_name='MessageId',
            new_name='messageId',
        ),
        migrations.RenameField(
            model_name='noticemessages',
            old_name='NoticeId',
            new_name='noticeId',
        ),
        migrations.RenameField(
            model_name='rewardmessages',
            old_name='MessageId',
            new_name='messageId',
        ),
        migrations.RenameField(
            model_name='rewardmessages',
            old_name='RewardId',
            new_name='rewardId',
        ),
        migrations.RenameField(
            model_name='sharemessages',
            old_name='MessageId',
            new_name='messageId',
        ),
        migrations.RenameField(
            model_name='sharemessages',
            old_name='ShareId',
            new_name='shareId',
        ),
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
