# Generated by Django 5.0.7 on 2024-12-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_comments_commentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='creatorId',
            field=models.IntegerField(default=0),
        ),
    ]
