# Generated by Django 5.0.7 on 2024-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_comments_creatorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='messageId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='消息ID'),
        ),
    ]
