# Generated by Django 5.0.7 on 2024-12-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
